"""Question parser (qtype, entities, query terms) and hop-1 retrieval."""
import sys, pathlib  # bootstrap: make the repo root importable
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import re

import config
from agent.entities import tokenize
from agent.state import ResearchState
from retrieval.bm25 import bm25_search
from retrieval.boolean import boolean_and, boolean_or

_BOTH_SAME = re.compile(r"\b(both|same)\b", re.I)
_WHICH_CMP = re.compile(r"\bwhich\b.*\b(first|older|younger|earlier|later|more|less|longer|shorter)\b", re.I)


def classify_qtype(question: str, entities: list[tuple[str, list[int], int]]) -> str:
    """Query classification: comparison if 'or' joins two linked entities, 'both'/'same', or 'which ... <comparative>'."""
    if _BOTH_SAME.search(question) or _WHICH_CMP.search(question):
        return "comparison"
    tokens = tokenize(question)
    spans = [(start, start + len(surface.split())) for surface, _, start in entities]
    for i, tok in enumerate(tokens):
        if tok != "or":
            continue
        if any(end <= i for _, end in spans) and any(start > i for start, _ in spans):
            return "comparison"
    return "bridge"


def parse(question: str, res, qid: str = "") -> ResearchState:
    """Query analysis: question type, idf-weighted query terms and linked question entities."""
    index = res.index
    entities = res.linker.link(question)
    state = ResearchState(qid=qid, question=question)
    state.qtype = classify_qtype(question, entities)
    state.query_terms = {t: index.idf(t) for t in index.analyze(question)}
    state.known_entities = {surface for surface, _, _ in entities}
    return state


def hop1(state: ResearchState, res) -> list[tuple[int, float]]:
    """Hop 1: Boolean AND over the top-idf terms (OR fallback) union free-text BM25, ranked by BM25."""
    index = res.index
    terms = index.analyze(state.question)
    top_terms = sorted(state.query_terms, key=lambda t: (-state.query_terms[t], t))[:config.BOOL_TOP_TERMS]
    bool_docs, df_order = boolean_and(index, top_terms)
    mode = "and"
    if len(bool_docs) < config.TOP_K:
        bool_docs, mode = boolean_or(index, top_terms), "or"
    free = bm25_search(index, terms, config.FREE_TEXT_K)
    candidates = set(bool_docs) | {d for d, _ in free}
    ranking = bm25_search(index, terms, config.TOP_K, candidates=candidates) if candidates else []
    state.hops.append({"hop": 1, "query": terms, "boolean_terms": top_terms, "df_order": df_order,
                       "boolean_mode": mode, "boolean_count": len(bool_docs), "free_text_count": len(free),
                       "candidates": len(candidates), "results": ranking})
    state.visited_docs.update(d for d, _ in ranking)
    return ranking


def main() -> None:
    """Parser diagnostics: qtype accuracy on EVAL (writes results/parser_accuracy.md) and hop-1 recall@20 on TUNE."""
    import json
    from collections import Counter
    from agent.resources import load_resources

    res = load_resources("dev", with_ranker=False)
    with open(config.DATA_PROCESSED / "questions_dev.jsonl", encoding="utf-8") as f:
        qrecs = {q["qid"]: q for q in map(json.loads, f)}
    split = lambda name: json.loads((config.DATA_PROCESSED / f"split_{name}.json").read_text(encoding="utf-8"))

    confusion = Counter()
    for qid in split("eval"):
        q = qrecs[qid]
        confusion[(q["type"], classify_qtype(q["question"], res.linker.link(q["question"])))] += 1
    n = sum(confusion.values())
    correct = sum(c for (gold, pred), c in confusion.items() if gold == pred)
    labels = ("bridge", "comparison")
    lines = ["# Parser question-type accuracy (EVAL)", "",
             f"Rule-based qtype vs HotpotQA `type` on {n} EVAL questions: **accuracy {correct / n:.3f}** "
             f"({correct}/{n}).", "", "| gold \\ predicted | bridge | comparison | total | recall |",
             "|---|---|---|---|---|"]
    for gold in labels:
        row = [confusion[(gold, p)] for p in labels]
        lines.append(f"| {gold} | {row[0]} | {row[1]} | {sum(row)} | {confusion[(gold, gold)] / max(sum(row), 1):.3f} |")
    prec = [confusion[(p, p)] / max(sum(confusion[(g, p)] for g in labels), 1) for p in labels]
    lines += [f"| precision | {prec[0]:.3f} | {prec[1]:.3f} | | |", "",
              "Generated by `python agent/parser.py`."]
    out = config.RESULTS_DIR / "parser_accuracy.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))

    tune = split("tune")[:100]
    hit_any = hit_both = 0
    for qid in tune:
        q = qrecs[qid]
        gold = {res.title2doc[t] for t in q["gold_titles"]}
        top = {d for d, _ in hop1(parse(q["question"], res, qid), res)}
        hit_any += bool(gold & top)
        hit_both += gold <= top
    print(f"\nhop-1 on {len(tune)} TUNE questions: recall@20 (>=1 gold) {hit_any / len(tune):.3f}, "
          f"both golds {hit_both / len(tune):.3f}")


if __name__ == "__main__":
    main()
